### ISSUE TITLE
Unable to create user after installing it using docker compose 

### ISSUE THREAD

**Issue by rajaseg** [JhumanJ/OpnForm#194]
Hi Team,
Thank you very much for a good product. I am trying to self host it using docker compose. I was able to access the web ui, but unable to create user (Create an account button spins but nothing happens).

Please find the configurations files below.

#### docker-compose
```
version: "3.7"

services:
  opnform:
    image: jhumanj/opnform
    container_name: opnform
    restart: unless-stopped
    volumes:
      - ./forms:/persist
      - ./my-env.env:/app/.env
    networks:
      - inet
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    networks:
      - inet
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=opnform
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - inet
```
#### Environment file
```
APP_NAME="OpnForm"
APP_ENV=production
APP_KEY=secretkey
APP_URL=http://opnform.example.com

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=opnform
DB_USERNAME=user
DB_PASSWORD=password

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.example.com
MAIL_PORT=587
MAIL_USERNAME=username
MAIL_PASSWORD=password
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=sender@example.com
MAIL_FROM_NAME="${APP_NAME}"

JWT_TTL=1440
JWT_SECRET=secret
```
![image](https://github.com/JhumanJ/OpnForm/assets/633479/39e36e1f-0635-485d-bdc6-fa669ac11fe1)

Am i doing anything wrong or something misconfigured?
