### ISSUE TITLE
cant get app running in a subdirectory

### ISSUE THREAD

**Issue by gilesbradshaw** [JhumanJ/OpnForm#337]
I am running with docker:

```
version: "3.7"

services:
  opnform:
    image: jhumanj/opnform:latest
    volumes:
      - forms:/persist
      - ./nuxt.env:/app/client/.env
      - ./laravel.env:/app/.env
    networks:
      - externalnet

volumes:
  forms:
networks:
  externalnet:
    driver: overlay
    external: true

```

/app/.env has:

```
APP_URL=https://subdomain.mydomain.com/opnform

```

/app/client/.env has 

```
NUXT_PUBLIC_APP_URL=https://subdomain.mydomain.com/opnform/
NUXT_PUBLIC_API_BASE=https://subdomain.mydomain.com/opnform/api

```

However the system shows symptoms of these not being respected (resources trying to load from root).

I also tried putting invalid domain and it doesn't seem to make any difference.

I wonder if app just won't run in a sub directory or if it's something else.

To be clear I am using a reverse proxy to incorperate this app into my web site  so when external request request  https://subdomain.mydomain.com/opnform/_nuxt/moderator.At5Sz9-h.js/ is made you will get a request on /_nuxt/moderator.At5Sz9-h.js/ - but I would expect link on web site to be /opnform/_nuxt/moderator.At5Sz9-h.js/
