### ISSUE TITLE
Session not working

### ISSUE THREAD

**Issue by mariogussnig** [JhumanJ/OpnForm#457]
Hello. I am running OpnForm in Docker with a pretty simple docker compose file. I already tried making changes in the environment files like `NUXT_PUBLIC_APP_URL` and `NUXT_PUBLIC_API_BASE` but i can't get the user to stay logged in on refresh. The closest thing to staying logged in is getting the user to be undefined, which i achieved by setting `NUXT_PUBLIC_API_BASE=/api`. I have been trying to solve this problem for quite a while now and hope you can help me out.
<br>
![image](https://github.com/JhumanJ/OpnForm/assets/96201208/b8c2f349-7444-4516-b9da-40949e605b84)
Output of `docker logs opnform` with params `NUXT_PUBLIC_API_BASE=https://mydomain/api`, `NUXT_PUBLIC_APP_URL=https://mydomain`
<br>
![image](https://github.com/JhumanJ/OpnForm/assets/96201208/9eaa79f1-7a6a-4425-9cc4-b0b81b6479ba)
![image](https://github.com/JhumanJ/OpnForm/assets/96201208/90e5c3b4-4c5c-467a-bfb2-028e6b94bbd4)
Screenshots of inspector and site with param `NUXT_PUBLIC_API_BASE=/api`

My docker compose file
```yaml
services:
    opnform:
        container_name: opnform
        volumes:
            - ./opnform-data:/persist
            - ./.env:/app/.env
            - ./.env.client:/app/client/.env
        ports:
            - 4001:80
        image: jhumanj/opnform
```
