### ISSUE TITLE
[BUG] API error: Origin IP is invalid

### ISSUE THREAD

**Issue by rl1987** [JhumanJ/OpnForm#646]
**Describe the bug**

**To Reproduce**

1. Login in with `admin@opnform.com` / `password` credentials.
2. Go to Admin -> Settings -> Profile page/tab.
3. Enter another email and press "Save changes" (with Chrome Devtools open).
4. Notice the error on API call:

```
{"message":"Origin IP is invalid"}
```

**Expected behavior**

All API calls should work without auth errors.

**Screenshots**

<img width="1440" alt="Screenshot 2024-12-13 at 14 25 48" src="https://github.com/user-attachments/assets/a801ea2b-f821-41df-b4bf-7f89e62fc378" />

**Environment (please complete the following information):**

-   Envionement - self hosted Docker deployment with custom DNS name and X.509 cert.
-   Browser - Chrome.
-   OpnForm Version -  1.4.5

**Additional context**

Modified Docker Compose config:

```yaml
---
services:
  api: &api
    image: jhumanj/opnform-api:latest
    environment: &api-environment  # Add this anchor
      DB_HOST: db
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      FILESYSTEM_DISK: local
      LOCAL_FILESYSTEM_VISIBILITY: public
    env_file: 
    - ./api/.env
    restart: always
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  api-worker:
    image: jhumanj/opnform-api:latest
    command: php artisan queue:work
    restart: always
    environment:
      <<: *api-environment
      IS_API_WORKER: "true"
    env_file: 
    - ./api/.env
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  ui:
    image: jhumanj/opnform-client:latest
    restart: always
    env_file: 
    - ./client/.env

  redis:
    image: redis:7
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-forge}
      POSTGRES_USER: ${DB_USERNAME:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-forge}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ingress:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: "[REDACTED]"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
      - nginx_secrets:/etc/letsencrypt          
      - ./user_conf.d:/etc/nginx/user_conf.d   
    ports:
      - 80:80
      - 443:443

volumes:
  postgres-data:
  opnform_storage:
  nginx_secrets:

```

Nginx config:

```
server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name opnform.keyspace.dev;
    root        /app/public;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/test-name/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/test-name/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    access_log /dev/stdout;
    error_log  /dev/stderr error;

    index index.html index.htm index.php;

    location / {
      proxy_http_version 1.1;
      proxy_pass http://ui:3000;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }

    location ~/(api|open|local\/temp|forms\/assets)/ {
         set $original_uri $uri;
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
       fastcgi_split_path_info ^(.+\.php)(/.+)$;
       fastcgi_pass api:9000;
       fastcgi_index index.php;
       include fastcgi_params;
       #fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/$fastcgi_script_name;
       fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/public/index.php;
       fastcgi_param REQUEST_URI $api_uri;
    }
}

```

Environment variables were updated with custom domains and HTTPS URLs.
