### ISSUE TITLE
[DEPLOYMENT] Only Nginx page visible

### ISSUE THREAD

**Issue by MarcS1975** [JhumanJ/OpnForm#678]
**Describe the issue**
I can deploy via Docker compose file and adding some env variables into Portainer, but when I access localhost:80 I only get the Nginx default start page.

**Deployment Environment**

-   Hosting Platform: Self-hosted Debian server

**Deployment Method**

-   [x] Docker

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. adapt compose file
2. launch via Portainer

**Error Messages**
All containers starting fine
When accesing localhost:8380 I only get the Nginx welcome pag

**Configuration Files**
```
services:
  api: &api
   image: jhumanj/opnform-api:latest
   environment: &api-environment  # Add this anchor
     DB_HOST: db
     REDIS_HOST: redis
     DB_DATABASE: Postgres-forge
     DB_USERNAME: pguser-forge
     DB_PASSWORD: pwd
     DB_CONNECTION: Postgres-pgsql
     FILESYSTEM_DISK: local
     LOCAL_FILESYSTEM_VISIBILITY: public
   #env_file: 
   #- ./api/.env
  volumes:
  - /Opnform:/usr/share/nginx/html/storage:rw

  api-worker:
    image: jhumanj/opnform-api:latest
    command: php artisan queue:work
    environment:
      <<: *api-environment
      IS_API_WORKER: "true"
  #  env_file: 
  #  - ./api/.env
    volumes:
    - /Opnform:/usr/share/nginx/html/storage:rw

  ui:
    image: jhumanj/opnform-client:latest
 #   env_file: 
 #   - ./client/.env

  redis:
    image: redis:7

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Postgres-forge
      POSTGRES_USER: pguser-forge
      POSTGRES_PASSWORD: pwd
    volumes:
      - /Opnform/postgres-data:/var/lib/postgresql/data
  ingress:
    image: nginx:1
    volumes:
      - /Opnform/docker/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 8083:80
volumes:
  postgres-data:
  opnform_storage:
```

**Logs**
To help us diagnose the issue, please provide the following logs:

-   `laravel.log` in `api/storage/logs` on the back-end image
-   Nuxt logs in the client docker logs

**Additional context**
Add any other context about the deployment issue here.
