### ISSUE TITLE
[DEPLOYMENT] "E" Variable not set & role "forge" does not exist

### ISSUE THREAD

**Issue by BNC-Philipp** [JhumanJ/OpnForm#781]
**Describe the issue**
I'm trying to set up a self-hosted docker environment. I'm running into two major problems:

1. When I start docker-compose I get the warning that some "E" variable isn't set and therefore defaults to an empty string.
2. The docker output (starting docker-compose up without -d) recurrently every 30 sec shows: 
opnform-db             | 2025-06-11 11:19:22.553 UTC [530] FATAL:  role "forge" does not exist

Now I'm wondering if actually my .env variables are actually not used in the databases.

**Deployment Environment**
-   OpnForm Version: latest (1.7.3)
-   Hosting Platform: Azure, Ubuntu VM _(Version:  Linux version 6.11.0-1015-azure (buildd@lcy02-amd64-036) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04))_
-   OS: Ubuntu 24.04.02

**Deployment Method**

-   [x] Docker
-   [ ] Manual installation
-   [ ] Other (please specify)

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. Pulled github
2. Executed Docker install script
3. Put Containers down to edit .env's
4. Restarted docker

**Error Messages**

1. When starting docker-compose up: WARN[0000] The "E" variable is not set. Defaulting to a blank string. --> this message appears 3 times
2. docker output (recurrently every 30 sec): 
opnform-db             | 2025-06-11 11:32:24.366 UTC [778] FATAL:  role "forge" does not exist

**Configuration Files**
docker-compose.yml
```
---
services:
  api: &api-environment
    image: jhumanj/opnform-api:latest
    container_name: opnform-api
    volumes: &api-environment-volumes
      - opnform_storage:/usr/share/nginx/html/storage:rw
    environment: &api-env
      APP_ENV: production
      # Database settings
      DB_HOST: db
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-forge}
      # PHP Configuration
      PHP_MEMORY_LIMIT: "1G"
      PHP_MAX_EXECUTION_TIME: "600"
      PHP_UPLOAD_MAX_FILESIZE: "64M"
      PHP_POST_MAX_SIZE: "64M"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy # Depend on redis being healthy too
    healthcheck:
      test: ["CMD-SHELL", "php /usr/share/nginx/html/artisan about || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

  api-worker:
    <<: *api-environment
    container_name: opnform-api-worker
    command: ["php", "artisan", "queue:work"]
    environment:
      <<: *api-env
      APP_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'php artisan queue:work' > /dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  api-scheduler:
    <<: *api-environment
    container_name: opnform-api-scheduler
    command: ["php", "artisan", "schedule:work"]
    environment:
      <<: *api-env
      APP_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "php /usr/share/nginx/html/artisan app:scheduler-status --mode=check --max-minutes=3 || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 70s # Allow time for first scheduled run and cache write

  ui:
    image: jhumanj/opnform-client:latest
    container_name: opnform-client
    env_file:
      - ./client/.env
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  redis:
    image: redis:7
    container_name: opnform-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 5s

  db:
    image: postgres:16
    container_name: opnform-db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-forge}
      POSTGRES_USER: ${DB_USERNAME:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bnc16825334fjnisiaad}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-forge}"]
      interval: 30s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ingress:
    image: nginx:1
    container_name: opnform-ingress
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 8081:80
    environment:
      - NGINX_MAX_BODY_SIZE=64m
    depends_on:
      api:
        condition: service_started
      ui:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
  opnform_storage:
```

.env in api/.env

```
APP_NAME="OpnForm"
APP_ENV=production
APP_KEY=base64:**secret**
APP_DEBUG=false
APP_URL=**secret**

SELF_HOSTED=true

LOG_CHANNEL=errorlog
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=**secret**
DB_USERNAME=**secret**
DB_PASSWORD=**secret**

FILESYSTEM_DRIVER=local
LOCAL_FILESYSTEM_VISIBILITY=public

CACHE_DRIVER=redis

QUEUE_CONNECTION=redis
SESSION_DRIVER=redis

MAIL_MAILER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=**secret**
MAIL_PASSWORD=**secret**
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=**secret**
MAIL_FROM_NAME=**secret**

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

JWT_TTL=1440
JWT_SECRET=**secret**
JWT_SKIP_IP_UA_VALIDATION=true

OPEN_AI_API_KEY=**secret**

H_CAPTCHA_SITE_KEY=
H_CAPTCHA_SECRET_KEY=

RE_CAPTCHA_SITE_KEY=
RE_CAPTCHA_SECRET_KEY=

TELEGRAM_BOT_ID=
TELEGRAM_BOT_TOKEN=

SHOW_OFFICIAL_TEMPLATES=true
FRONT_API_SECRET=**secret**
```

.env in client/.env

```
NUXT_PUBLIC_APP_URL=https://forms.mydomain.com
NUXT_PUBLIC_API_BASE=https://forms.mydomain.com/api
NUXT_PRIVATE_API_BASE=http://ingress/api
NUXT_PUBLIC_ENV=dev
NUXT_PUBLIC_H_CAPTCHA_SITE_KEY=
NUXT_PUBLIC_RE_CAPTCHA_SITE_KEY=
NUXT_PUBLIC_ROOT_REDIRECT_URL=https://mydomain.com
NUXT_API_SECRET=**secret**
```

**Logs**
To help us diagnose the issue, please provide the following logs:

-   `laravel.log` in `api/storage/logs` on the back-end image: **Folder is empty**
-   Nuxt logs in the client docker logs: Don't know where to find them.

**Additional context**
I also tried to take the defaults out of the variables ${DB_DATABASE}, but then the Error Messages where like:
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string.

**Comment by BNC-Philipp** [comment]
And there is a 3rd issue, that i just noticed: Docker adds a new cryptic volume on every container startup. But data is persistent as far as I can judge. Also my ubuntu server tells me upon login: There are 2 zombie processes. Is that normal?

```
VOLUME NAME                                                        LINKS     SIZE
fb16044ac2bad0652a4e92236a9d806b64391231c7ff0fb5549157cfd71fe38c   1         0B
opnform_opnform_storage                                            3         129.5kB
opnform_postgres-data                                              1         49.26MB
53a34aa8ee59c4992469697a0f2278d80d6f07a0d86ebfaa577e4d5f821303ac   0         35.83kB
fc87d2e85436060a89303b5fd96969026c7375296f90fa8be864502f380d0dbb   0         12.64kB
```

**Comment by JhumanJ** [comment]
Hey - seems like your .env file is not read since it's trying to use the default credentials of the docker compose to interract with DB (forge)

**Comment by BNC-Philipp** [comment]
> Hey - seems like your .env file is not read since it's trying to use the default credentials of the docker compose to interract with DB (forge)

Sorry I didn't quite give you the correct information here: actually I already changed the defaults in my docker-compose to the actual env values, because I suspected, that the .env variables aren't used. But in the message above I reversed it to -forge to secure my data. So long story short: There is no forge in the docker-compose and also not in the .env file. That's why I'm wondering about this docker output.

**Comment by JhumanJ** [comment]
Ok so you hardcoded everything in the docker compose file and it dind't work? WHat's the error then?

**Comment by BNC-Philipp** [comment]
Generally everything is working (now), but:
- I only changed (hardcoded) the default values, because I was suspecting, that some .env variables are not used. Why do I suspect so: because when I deleted the defaults in the docker-compose.yml (instead of ${DB_DATABASE:-forge} --> ${DB_DATABASE} and recreated the whole docker setup, there was no connection to the databases possible anymore and those errors popped up (in the docker output):
_WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string._
_WARN[0000] The "DB_USERNAME" variable is not set. Defaulting to a blank string._
etc...

I mean as long as you don't change the ${DB_DATABASE:-forge} you would not even notice, that .env variables might not be used. Maybe others have similar issues, but did'nt notice it.

- another error is the: _opnform-db | 2025-06-11 11:32:24.366 UTC [778] FATAL: role "forge" does not exist_ in the docker output
this error is still coming, though I changed the default values in the docker-compose.yml to my own ones. Why is that error coming though there is no "forge" in any .env or .yml file anymore.
- lastly: Docker adds a new cryptic volume on every container startup. Also my ubuntu server tells me upon login: There are 2 zombie processes. Is that normal? What are those volumes and zombie processes. (also the system RAM is getting fuller and fuller with every compose up/down). I might be doing something wrong, as I'm not a programmer. But maybe someone has similar problems.

![Image](https://github.com/user-attachments/assets/048f1f23-9eb2-4185-b5dc-1eba2924fa64)
![Image](https://github.com/user-attachments/assets/5cc91d8d-9de6-4ad5-a127-238ac0f6ce9f)
![Image](https://github.com/user-attachments/assets/8d68600f-5f71-4624-b4e9-d990f2be1f76)

**Comment by JhumanJ** [comment]
`forge` is used as a fallback value for both `DB_DATABASE` and `DB_USERNAME` at the application level if absent from the ENV. So I really think you have an issue loading the env files in your docker setup here
I'm not sure about these zombie volume & processes but I'll take a look!

**Comment by BNC-Philipp** [comment]
Another remark to the .env files: All the other values from the files are used in the container (like APP_URL, OPEN_AI_API_KEY, etc.). It only affects the ones that are used as variables in the docker-compose.yml. 

Also in [this](https://stackoverflow.com/questions/64723235/docker-compose-environment-variables-blank-string#:~:text=Additionally%20with%20docker%2Dcompose%20you%20can%20use%20a%20.env%20file%20in%20the%20current%20directory.) stackoverflow post someone claims that variables in a docker-compose.yml can only be drawn from an .env file located in the root directory (meaning the same as where the docker-compose.yml is located).

**Comment by JhumanJ** [comment]
I believe that this is only the case when env file is not explicitely specified in the docker compose file. Please check https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute.

I'll publish a new release later today changing some things about the docker setup, so I'll close this for now. Please try again tomorrow and re-open an issue if needed, thanks

**Comment by filipesmedeiros** [comment]
I'm also having some issues with env vars. For example, without having the `forge` value anywhere for the `DB_DATABASE`, I get error logs saying that something is trying to connect to that database. Which, to me, signals that the env vars are not being correctly read sometimes. Since I use Portainer and this is only happening with OpnForm, I think there might be something going on. I will test further.

**Comment by filipesmedeiros** [comment]
After some trials of different configs, weird behaviour persists.

For example, I'm getting this in my database (standard Postgres image) container logs:

```
2026-07-08 17:59:54.452 UTC [42] FATAL:  database "forge" does not exist
2026-07-08 18:00:24.565 UTC [53] FATAL:  database "forge" does not exist
2026-07-08 18:00:54.672 UTC [61] FATAL:  database "forge" does not exist
2026-07-08 18:01:24.778 UTC [69] FATAL:  database "forge" does not exist
2026-07-08 18:01:54.907 UTC [76] FATAL:  database "forge" does not exist
2026-07-08 18:02:25.063 UTC [85] FATAL:  database "forge" does not exist
2026-07-08 18:02:55.229 UTC [93] FATAL:  database "forge" does not exist
```

When my `docker-compose.yml` (actually the config inside Portainer, but should be the same) looks like this:

```
services:
  api: &api-environment
    image: jhumanj/opnform-api:1.13.1
    volumes: &api-environment-volumes
      - opnform-storage:/usr/share/nginx/html/storage:rw
    environment: &api-env
      APP_ENV: production
      # Database settings
      DB_HOST: db
      REDIS_HOST: cache
      DB_DATABASE: formularios
      DB_PASSWORD: REDACTED
      DB_USERNAME: forge
      DB_CONNECTION: pgsql
      # PHP Configuration
      PHP_MEMORY_LIMIT: 1G
      PHP_MAX_EXECUTION_TIME: 600
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      APP_NAME: REDACTED
      APP_KEY: REDACTED
      APP_DEBUG: false
      APP_URL: https://REDACTED
      LOG_CHANNEL: errorlog
      LOG_LEVEL: info
      FILESYSTEM_DRIVER: local
      LOCAL_FILESYSTEM_VISIBILITY: public
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      MAIL_MAILER: smtp
      MAIL_HOST: REDACTED
      MAIL_PORT: 587
      MAIL_USERNAME: REDACTED
      MAIL_PASSWORD: REDACTED
      MAIL_ENCRYPTION: TLS
      MAIL_FROM_ADDRESS: REDACTED
      MAIL_FROM_NAME: REDACTED
      JWT_TTL: 1440
      JWT_SECRET: REDACTED
      JWT_SKIP_IP_UA_VALIDATION: true
      SHOW_OFFICIAL_TEMPLATES: true
      FRONT_API_SECRET: REDACTED
      OIDC_FORCE_LOGIN: false
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php /usr/share/nginx/html/artisan about || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

  api-worker:
    <<: *api-environment
    command: ["php", "artisan", "queue:work"]
    environment:
      <<: *api-env
    healthcheck:
      test:
        ["CMD-SHELL", "pgrep -f 'php artisan queue:work' > /dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  api-scheduler:
    <<: *api-environment
    command: ["php", "artisan", "schedule:work"]
    environment:
      <<: *api-env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "php /usr/share/nginx/html/artisan app:scheduler-status --mode=check --max-minutes=3 || exit 1",
        ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 70s # Allow time for first scheduled run and cache write

  ui:
    image: jhumanj/opnform-client:1.13.1
    environment:
      NUXT_PUBLIC_APP_URL: /
      NUXT_PUBLIC_API_BASE: /api
      NUXT_PRIVATE_API_BASE: http://ingress/api
      NUXT_PUBLIC_ENV: prod
      NUXT_PUBLIC_ROOT_REDIRECT_URL: https://REDACTED/home
      NUXT_API_SECRET: REDACTED
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "wget --spider -q http://localhost:3000/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  cache:
    image: valkey/valkey:9
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: formularios
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: forge
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "forge" ]
      interval: 30s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql:rw

  ingress:
    image: nginx:1
    volumes:
      - /docker/formularios/nginx.conf:/etc/nginx/templates/default.conf.template:rw
    environment:
      - NGINX_MAX_BODY_SIZE=64m
    depends_on:
      api:
        condition: service_healthy
      ui:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - default

volumes:
  db-data:
  opnform-storage:
```

As you can see, there is no "forge" database anywhere in sight.

Other weird things:
1. everything seems to work fine, even with the errors
2. the errors are only logged every 30s
3. if I name my `POSTGRES_USER: postgres`, then the error will be, instead, `role "root" does not exist`, which I think is even weirder…

Can we maybe reopen this issue, @JhumanJ, since the problem with env vars seems to persist?
